export const GRIEVANCES = [
  {
    key: "1",
    grn: "GRN/2026/DPB/001245",
    subject: "Unauthorized data sharing with third parties",
    respondent: "TechHub Solutions Pvt Ltd",
    category: "consent-violation",
    priority: "urgent",
    scrutinyLevel: "Level 1",
    assignedTo: "Me",
    filedDate: "2026-04-28",
    deadline: "2026-05-05",
    status: "pending",
  },
  {
    key: "2",
    grn: "GRN/2026/DPB/001243",
    subject: "Data breach - customer data exposed online",
    respondent: "ShopFast India",
    category: "data-breach",
    priority: "high",
    scrutinyLevel: "Level 2",
    assignedTo: "Rajesh Kumar",
    filedDate: "2026-04-27",
    deadline: "2026-05-04",
    status: "under-review",
  },
  {
    key: "3",
    grn: "GRN/2026/DPB/001240",
    subject: "Failure to honor data deletion request",
    respondent: "DataStore Corp",
    category: "right-to-erasure",
    priority: "medium",
    scrutinyLevel: "Level 1",
    assignedTo: "Amit Verma",
    filedDate: "2026-04-26",
    deadline: "2026-05-03",
    status: "clarification-requested",
  },
  {
    key: "4",
    grn: "GRN/2026/DPB/001238",
    subject: "Incorrect personal data maintained",
    respondent: "FinTech Services Ltd",
    category: "right-to-correction",
    priority: "medium",
    scrutinyLevel: "Level 1",
    assignedTo: "Me",
    filedDate: "2026-04-25",
    deadline: "2026-05-12",
    status: "pending",
  },
  {
    key: "5",
    grn: "GRN/2026/DPB/001236",
    subject: "Refusal to provide data access copy",
    respondent: "HealthTrack India",
    category: "right-to-access",
    priority: "high",
    scrutinyLevel: "Level 2",
    assignedTo: "Amit Verma",
    filedDate: "2026-04-24",
    deadline: "2026-05-14",
    status: "under-review",
  },
  {
    key: "6",
    grn: "GRN/2026/DPB/001234",
    subject: "Unauthorized marketing communications sent",
    respondent: "BuyNow Platform",
    category: "consent-violation",
    priority: "low",
    scrutinyLevel: "Level 1",
    assignedTo: "Rajesh Kumar",
    filedDate: "2026-04-23",
    deadline: "2026-05-16",
    status: "pending",
  },
  {
    key: "7",
    grn: "GRN/2026/DPB/001232",
    subject: "Data sold to third party without consent",
    respondent: "QuickLoan Corp",
    category: "consent-violation",
    priority: "urgent",
    scrutinyLevel: "Level 3",
    assignedTo: "Priya Sharma",
    filedDate: "2026-04-22",
    deadline: "2026-05-10",
    status: "pending",
  },
  {
    key: "8",
    grn: "GRN/2026/DPB/001230",
    subject: "Biometric data stored without permission",
    respondent: "SecureID Solutions",
    category: "sensitive-data",
    priority: "urgent",
    scrutinyLevel: "Level 2",
    assignedTo: "Amit Verma",
    filedDate: "2026-04-21",
    deadline: "2026-05-11",
    status: "under-review",
  },
  {
    key: "9",
    grn: "GRN/2026/DPB/001228",
    subject: "Failure to notify data breach within 72 hours",
    respondent: "CloudStorage Ltd",
    category: "data-breach",
    priority: "high",
    scrutinyLevel: "Level 2",
    assignedTo: "Rajesh Kumar",
    filedDate: "2026-04-20",
    deadline: "2026-05-13",
    status: "pending",
  },
  {
    key: "10",
    grn: "GRN/2026/DPB/001226",
    subject: "Excessive data collection beyond stated purpose",
    respondent: "EduLearn App",
    category: "data-minimization",
    priority: "medium",
    scrutinyLevel: "Level 1",
    assignedTo: "Priya Sharma",
    filedDate: "2026-04-19",
    deadline: "2026-05-17",
    status: "clarification-requested",
  },
  {
    key: "11",
    grn: "GRN/2026/DPB/001224",
    subject: "Withdrawal of consent not honored",
    respondent: "SocialNet India",
    category: "consent-violation",
    priority: "medium",
    scrutinyLevel: "Level 1",
    assignedTo: "Amit Verma",
    filedDate: "2026-04-18",
    deadline: "2026-05-15",
    status: "under-review",
  },
  {
    key: "12",
    grn: "GRN/2026/DPB/001222",
    subject: "Personal data used for profiling without consent",
    respondent: "AdTrack Solutions",
    category: "consent-violation",
    priority: "high",
    scrutinyLevel: "Level 2",
    assignedTo: "Rajesh Kumar",
    filedDate: "2026-04-17",
    deadline: "2026-05-18",
    status: "pending",
  },
  {
    key: "13",
    grn: "GRN/2026/DPB/001220",
    subject: "Data retention beyond stated period",
    respondent: "InsureCo Ltd",
    category: "data-retention",
    priority: "low",
    scrutinyLevel: "Level 1",
    assignedTo: "Priya Sharma",
    filedDate: "2026-04-16",
    deadline: "2026-05-20",
    status: "approved",
  },
  {
    key: "14",
    grn: "GRN/2026/DPB/001218",
    subject: "Cross-border data transfer without notification",
    respondent: "GlobalPay Services",
    category: "cross-border",
    priority: "high",
    scrutinyLevel: "Level 3",
    assignedTo: "Amit Verma",
    filedDate: "2026-04-15",
    deadline: "2026-05-19",
    status: "approved",
  },
  {
    key: "15",
    grn: "GRN/2026/DPB/001216",
    subject: "Denial of right to nominate data representative",
    respondent: "LegalAssist Online",
    category: "right-to-nominate",
    priority: "low",
    scrutinyLevel: "Level 1",
    assignedTo: "Rajesh Kumar",
    filedDate: "2026-04-14",
    deadline: "2026-05-21",
    status: "pending",
  },
];

export const PRIORITY_CLASS = {
  urgent: "red",
  high: "orange",
  medium: "blue",
  low: "default",
};

export const STATUS_DOT = {
  pending: "processing",
  "under-review": "processing",
  "clarification-requested": "warning",
  approved: "success",
  rejected: "error",
};

export const STATUS_LABEL = {
  pending: "Pending Review",
  "under-review": "Under Review",
  "clarification-requested": "Clarification Requested",
  approved: "Approved",
  rejected: "Rejected",
};

export function daysLeft(dateStr) {
  return Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86400000);
}
